#!/usr/bin/env node
/* Build stamp for PA-Helper. Hashes all repo files (except the generated version.js), records the
 * latest change time, and emits js/version.js with an incrementing build number.
 *
 * Versioning: v<MAJOR_MINOR>.<build>. MAJOR_MINOR is "0.1" during beta. The build number
 * auto-increments each run and RESETS to 1 when MAJOR_MINOR changes (a minor bump = a milestone).
 * Bump MAJOR_MINOR below when you roll the minor version; set it to "1.0" for the first release.
 *
 * Re-run after edits:  node tools/stamp.js
 */
const fs = require("fs"), crypto = require("crypto"), path = require("path");
const MAJOR_MINOR = "0.1";
const root = path.resolve(__dirname, "..");
const versionPath = path.join(root, "js", "version.js");
const files = [];
(function walk(d) {
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    if (e.name === "node_modules" || e.name.startsWith(".")) continue;
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p);
    else if (p !== versionPath) files.push(p);
  }
})(root);
files.sort();
const h = crypto.createHash("sha256");
let latest = 0;
for (const f of files) { h.update(f.slice(root.length)); h.update(fs.readFileSync(f)); const m = fs.statSync(f).mtimeMs; if (m > latest) latest = m; }
const hash = h.digest("hex").slice(0, 10);
const d = new Date(latest), pad = (n) => String(n).padStart(2, "0");
const date = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;

// carry the build number forward (reset if the minor version rolled)
let build = 1;
try {
  const prev = fs.readFileSync(versionPath, "utf8");
  const pv = (prev.match(/version:\s*"([^"]+)"/) || [])[1] || "";
  const pmm = pv.split(".").slice(0, 2).join(".");
  const pb = parseInt((prev.match(/build:\s*(\d+)/) || [])[1] || "0", 10);
  if (pmm === MAJOR_MINOR) build = pb + 1;
} catch (e) { /* first stamp under this scheme */ }
const version = `${MAJOR_MINOR}.${build}`;

fs.writeFileSync(versionPath,
  `/* auto-generated by tools/stamp.js — do not edit by hand */\n` +
  `window.PA_VERSION = { version: "${version}", build: ${build}, hash: "${hash}", date: "${date}" };\n`);
console.log("stamped v" + version, hash, date, `(${files.length} files)`);
