#!/usr/bin/env node
/* Build stamp for PA-Helper (no VCS yet): hashes all repo files (except the generated
 * version.js) and records the latest change time, writing js/version.js.
 * Re-run after edits:  node tools/stamp.js
 */
const fs = require("fs"), crypto = require("crypto"), path = require("path");
const root = path.resolve(__dirname, "..");
const files = [];
(function walk(d) {
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    if (e.name === "node_modules" || e.name.startsWith(".")) continue;
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p);
    else if (p !== path.join(root, "js", "version.js")) files.push(p);
  }
})(root);
files.sort();
const h = crypto.createHash("sha256");
let latest = 0;
for (const f of files) { h.update(f.slice(root.length)); h.update(fs.readFileSync(f)); const m = fs.statSync(f).mtimeMs; if (m > latest) latest = m; }
const hash = h.digest("hex").slice(0, 10);
const d = new Date(latest), pad = (n) => String(n).padStart(2, "0");
const date = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
fs.writeFileSync(path.join(root, "js", "version.js"),
  `/* auto-generated by tools/stamp.js — do not edit by hand */\nwindow.PA_VERSION = { hash: "${hash}", date: "${date}" };\n`);
console.log("stamped", hash, date, `(${files.length} files)`);
